FROM openjdk:8-jdk-alpine
ADD ./CitibikeApiProducer/build/libs/tw-citibike-apis-producer0.1.0.jar /app.jar
ENTRYPOINT java  -jar /app.jar --spring.profiles.active=e2e-nyc-status --spring.profiles.active=docker